AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template to scrape livetiming info using Python (no Docker)

Globals:
  Function:
    Timeout: 120
    MemorySize: 2048
    Runtime: python3.10
    Architectures:
      - x86_64

Resources:
  getLivetimingInfoFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handler
      CodeUri: src/

      Events:
        getLivetimingInfo:
          Type: Api
          Properties:
            Path: /get-livetiming-info
            Method: get

Outputs:
  getLivetimingInfoApi:
    Description: "API Gateway endpoint URL for Prod stage"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-livetiming-info/"
  getLivetimingInfoFunction:
    Description: "getLivetimingInfo Lambda Function ARN"
    Value: !GetAtt getLivetimingInfoFunction.Arn
  getLivetimingInfoFunctionIamRole:
    Description: "Implicit IAM Role created for getLivetimingInfo function"
    Value: !GetAtt getLivetimingInfoFunctionRole.Arn
