AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for get-points-list

Globals:
  Function:
    Timeout: 900
    MemorySize: 3008
    Runtime: python3.10
    Architectures:
      - x86_64

Resources:
  GetPointsListFunction:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: app.lambda_handler
      CodeUri: src/
      Events:
        GetPointsList:
          Type: Api 
          Properties:
            Path: /get-points-list
            Method: get

Outputs:
  GetPointsListApi:
    Description: "API Gateway endpoint URL for Prod stage for GetPointsList function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get-points-list/"
  GetPointsListFunction:
    Description: "GetPointsList Lambda Function ARN"
    Value: !GetAtt GetPointsListFunction.Arn
  GetPointsListFunctionIamRole:
    Description: "Implicit IAM Role created for GetPointsList function"
    Value: !GetAtt GetPointsListFunctionRole.Arn
